version: '3'
services:
 postgres:
  container_name: l_postgres
  hostname: postgres
  build:
    context: .
    dockerfile: postgres.dockerfile
  environment:
    POSTGRES_USER: luke
    POSTGRES_PASSWORD: 12345
    POSTGRES_DB: nodelogin
    PGDATA: /var/lib/postgresql/data/pgdata
  volumes:
    - /data/mount:/var/lib/postgresql/data
  #ports:
   #- "5436:5432"
  networks:
   - internal_network

 node:
  hostname: node
  ports:
    - "4000:4000"
  container_name: l_node
  restart: unless-stopped
  build:
   context: .
   dockerfile: node.dockerfile
  volumes:
   - ./:/app:rw
  networks:
   - internal_network

networks:
 internal_network:
  driver: bridge
